session_name: dev
windows:
- window_name: 
  panes:
    - glances
- window_name:  
  shell_command_before:
    - cd ~/Projects
  panes:
    - nvim
- window_name: 
  shell_command_before:
    - cd ~/Projects
  panes:
    -
    -

